// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaxService.Data.DataContext;

namespace TaxService.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210707131715_UpdatedTaxpayersIdsToNullable")]
    partial class UpdatedTaxpayersIdsToNullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TaxService.Domain.Model.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("InspectorId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InspectorId");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("TaxService.Domain.Model.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<byte[]>("File")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("TaxpayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TaxpayerId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("TaxService.Domain.Model.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TaxpayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TaxpayerId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("TaxService.Domain.Model.Inspector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Inspector");
                });

            modelBuilder.Entity("TaxService.Domain.Model.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TaxpayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TaxpayerId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TaxService.Domain.Model.PlaceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlaceType");
                });

            modelBuilder.Entity("TaxService.Domain.Model.ReportTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<byte[]>("File")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReportTemplates");
                });

            modelBuilder.Entity("TaxService.Domain.Model.ReportTemplateParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("ReportTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReportTemplateId");

                    b.ToTable("ReportTemplateParameter");
                });

            modelBuilder.Entity("TaxService.Domain.Model.TaxType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TaxType");
                });

            modelBuilder.Entity("TaxService.Domain.Model.Taxpayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text");

                    b.Property<int?>("AreaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Inn")
                        .HasColumnType("text");

                    b.Property<string>("Kpp")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Percent")
                        .HasColumnType("integer");

                    b.Property<string>("PlaceAddress")
                        .HasColumnType("text");

                    b.Property<int?>("PlaceTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("TaxTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PlaceTypeId");

                    b.HasIndex("TaxTypeId");

                    b.ToTable("Taxpayers");
                });

            modelBuilder.Entity("TaxService.Domain.Model.TaxpayerCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TaxpayerCategory");
                });

            modelBuilder.Entity("TaxService.Domain.Model.Area", b =>
                {
                    b.HasOne("TaxService.Domain.Model.Inspector", "Inspector")
                        .WithMany("Areas")
                        .HasForeignKey("InspectorId");

                    b.Navigation("Inspector");
                });

            modelBuilder.Entity("TaxService.Domain.Model.Document", b =>
                {
                    b.HasOne("TaxService.Domain.Model.Taxpayer", "Taxpayer")
                        .WithMany("Documents")
                        .HasForeignKey("TaxpayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Taxpayer");
                });

            modelBuilder.Entity("TaxService.Domain.Model.Income", b =>
                {
                    b.HasOne("TaxService.Domain.Model.Taxpayer", "Taxpayer")
                        .WithMany("Incomes")
                        .HasForeignKey("TaxpayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Taxpayer");
                });

            modelBuilder.Entity("TaxService.Domain.Model.Payment", b =>
                {
                    b.HasOne("TaxService.Domain.Model.Taxpayer", "Taxpayer")
                        .WithMany("Payments")
                        .HasForeignKey("TaxpayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Taxpayer");
                });

            modelBuilder.Entity("TaxService.Domain.Model.ReportTemplateParameter", b =>
                {
                    b.HasOne("TaxService.Domain.Model.ReportTemplate", null)
                        .WithMany("Parameters")
                        .HasForeignKey("ReportTemplateId");
                });

            modelBuilder.Entity("TaxService.Domain.Model.Taxpayer", b =>
                {
                    b.HasOne("TaxService.Domain.Model.Area", "Area")
                        .WithMany("Taxpayers")
                        .HasForeignKey("AreaId");

                    b.HasOne("TaxService.Domain.Model.TaxpayerCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("TaxService.Domain.Model.PlaceType", "PlaceType")
                        .WithMany()
                        .HasForeignKey("PlaceTypeId");

                    b.HasOne("TaxService.Domain.Model.TaxType", "TaxType")
                        .WithMany()
                        .HasForeignKey("TaxTypeId");

                    b.Navigation("Area");

                    b.Navigation("Category");

                    b.Navigation("PlaceType");

                    b.Navigation("TaxType");
                });

            modelBuilder.Entity("TaxService.Domain.Model.Area", b =>
                {
                    b.Navigation("Taxpayers");
                });

            modelBuilder.Entity("TaxService.Domain.Model.Inspector", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("TaxService.Domain.Model.ReportTemplate", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("TaxService.Domain.Model.Taxpayer", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Incomes");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
