//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaxpayerInfo", Namespace="http://schemas.datacontract.org/2004/07/TaxServiceLibrary.Model")]
    public partial class TaxpayerInfo : object
    {
        
        private string additionalInfoField;
        
        private System.DateTime beginDateField;
        
        private string categoryField;
        
        private ServiceReference1.DocumentInfo[] documentsField;
        
        private int idField;
        
        private string innField;
        
        private string kppField;
        
        private string nameField;
        
        private int percentField;
        
        private string placeAddressField;
        
        private string placeTypeField;
        
        private string taxTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string additionalInfo
        {
            get
            {
                return this.additionalInfoField;
            }
            set
            {
                this.additionalInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime beginDate
        {
            get
            {
                return this.beginDateField;
            }
            set
            {
                this.beginDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.DocumentInfo[] documents
        {
            get
            {
                return this.documentsField;
            }
            set
            {
                this.documentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string inn
        {
            get
            {
                return this.innField;
            }
            set
            {
                this.innField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string kpp
        {
            get
            {
                return this.kppField;
            }
            set
            {
                this.kppField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int percent
        {
            get
            {
                return this.percentField;
            }
            set
            {
                this.percentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string placeAddress
        {
            get
            {
                return this.placeAddressField;
            }
            set
            {
                this.placeAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string placeType
        {
            get
            {
                return this.placeTypeField;
            }
            set
            {
                this.placeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string taxType
        {
            get
            {
                return this.taxTypeField;
            }
            set
            {
                this.taxTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentInfo", Namespace="http://schemas.datacontract.org/2004/07/TaxServiceLibrary.Model")]
    public partial class DocumentInfo : object
    {
        
        private string descriptionField;
        
        private byte[] fileField;
        
        private int idField;
        
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportTemplateInfo", Namespace="http://schemas.datacontract.org/2004/07/TaxServiceLibrary.Model")]
    public partial class ReportTemplateInfo : object
    {
        
        private string descriptionField;
        
        private byte[] fileField;
        
        private int idField;
        
        private string nameField;
        
        private ServiceReference1.ReportTemplateParameterInfo[] parametersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.ReportTemplateParameterInfo[] parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportTemplateParameterInfo", Namespace="http://schemas.datacontract.org/2004/07/TaxServiceLibrary.Model")]
    public partial class ReportTemplateParameterInfo : object
    {
        
        private string defaultValueField;
        
        private string descriptionField;
        
        private int idField;
        
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string defaultValue
        {
            get
            {
                return this.defaultValueField;
            }
            set
            {
                this.defaultValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinOperationInfo", Namespace="http://schemas.datacontract.org/2004/07/TaxServiceLibrary.Model")]
    public partial class FinOperationInfo : object
    {
        
        private int amountField;
        
        private System.DateTime dateField;
        
        private int idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITaxService")]
    public interface ITaxService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxService/Login", ReplyAction="http://tempuri.org/ITaxService/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxService/GetTaxpayerList", ReplyAction="http://tempuri.org/ITaxService/GetTaxpayerListResponse")]
        System.Threading.Tasks.Task<ServiceReference1.TaxpayerInfo[]> GetTaxpayerListAsync(int inspectorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxService/GetReportTemplateList", ReplyAction="http://tempuri.org/ITaxService/GetReportTemplateListResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ReportTemplateInfo[]> GetReportTemplateListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxService/GetTaxpayerInfo", ReplyAction="http://tempuri.org/ITaxService/GetTaxpayerInfoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.TaxpayerInfo> GetTaxpayerInfoAsync(int taxpayerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxService/GetReportTemplateInfo", ReplyAction="http://tempuri.org/ITaxService/GetReportTemplateInfoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ReportTemplateInfo> GetReportTemplateInfoAsync(int templateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxService/SaveTaxpayerInfo", ReplyAction="http://tempuri.org/ITaxService/SaveTaxpayerInfoResponse")]
        System.Threading.Tasks.Task<bool> SaveTaxpayerInfoAsync(int inspectorId, ServiceReference1.TaxpayerInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxService/SaveReportTemplateInfo", ReplyAction="http://tempuri.org/ITaxService/SaveReportTemplateInfoResponse")]
        System.Threading.Tasks.Task<bool> SaveReportTemplateInfoAsync(ServiceReference1.ReportTemplateInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxService/GetIncomes", ReplyAction="http://tempuri.org/ITaxService/GetIncomesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.FinOperationInfo[]> GetIncomesAsync(int taxpayerId, System.DateTime from, System.DateTime to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaxService/GetPayments", ReplyAction="http://tempuri.org/ITaxService/GetPaymentsResponse")]
        System.Threading.Tasks.Task<ServiceReference1.FinOperationInfo[]> GetPaymentsAsync(int taxpayerId, System.DateTime from, System.DateTime to);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ITaxServiceChannel : ServiceReference1.ITaxService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class TaxServiceClient : System.ServiceModel.ClientBase<ServiceReference1.ITaxService>, ServiceReference1.ITaxService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TaxServiceClient() : 
                base(TaxServiceClient.GetDefaultBinding(), TaxServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITaxService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaxServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TaxServiceClient.GetBindingForEndpoint(endpointConfiguration), TaxServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaxServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TaxServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaxServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TaxServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TaxServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string login, string password)
        {
            return base.Channel.LoginAsync(login, password);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TaxpayerInfo[]> GetTaxpayerListAsync(int inspectorId)
        {
            return base.Channel.GetTaxpayerListAsync(inspectorId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ReportTemplateInfo[]> GetReportTemplateListAsync()
        {
            return base.Channel.GetReportTemplateListAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.TaxpayerInfo> GetTaxpayerInfoAsync(int taxpayerId)
        {
            return base.Channel.GetTaxpayerInfoAsync(taxpayerId);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ReportTemplateInfo> GetReportTemplateInfoAsync(int templateId)
        {
            return base.Channel.GetReportTemplateInfoAsync(templateId);
        }
        
        public System.Threading.Tasks.Task<bool> SaveTaxpayerInfoAsync(int inspectorId, ServiceReference1.TaxpayerInfo info)
        {
            return base.Channel.SaveTaxpayerInfoAsync(inspectorId, info);
        }
        
        public System.Threading.Tasks.Task<bool> SaveReportTemplateInfoAsync(ServiceReference1.ReportTemplateInfo info)
        {
            return base.Channel.SaveReportTemplateInfoAsync(info);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.FinOperationInfo[]> GetIncomesAsync(int taxpayerId, System.DateTime from, System.DateTime to)
        {
            return base.Channel.GetIncomesAsync(taxpayerId, from, to);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.FinOperationInfo[]> GetPaymentsAsync(int taxpayerId, System.DateTime from, System.DateTime to)
        {
            return base.Channel.GetPaymentsAsync(taxpayerId, from, to);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITaxService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITaxService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:1488/TaxService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TaxServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITaxService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TaxServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITaxService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITaxService,
        }
    }
}
